### ISSUE TITLE
AWS IAM Setup

### ISSUE THREAD

**Issue by alijnclarke** [c6fc/warcannon#5]
Hey, 
Trying to get this working, but when running ./warcannon fire, it's coming back with:

```
An error occurred (InvalidSpotFleetRequestConfig) when calling the RequestSpotFleet operation: Parameter: SpotFleetRequestConfig.IamFleetRole is invalid
```

Please could you explain which roles need to be created?

Thanks

**Comment by c6fc** [comment]
Thanks for trying it out. The role should be getting created during the 'warcannon deploy' step. The role used during the spot fleet request is defined here: https://github.com/c6fc/warcannon/blob/b5970ca9c8b10b7aac58a9f9c617ec92cfc4487d/jsonnet/ec2_spot_request.libsonnet#L2

Can you check whether the 'aws-ec2-spot-fleet-tagging-role' was created properly in your AWS account?

**Comment by alijnclarke** [comment]
Interestingly it didn't, I manually created the role and got a little further
```
The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.
``

Fixed it in the end with:
```
aws iam create-service-linked-role --aws-service-name spot.amazonaws.com
```

Now it's successfully building instances :)
