### ISSUE TITLE
Terraform 0.11 Dependency

### ISSUE THREAD

**Issue by un-fuf-a-doo** [c6fc/warcannon#6]
Why are you locking this dependency to something so old?  You do realize Terraform is on v1.08 now right?

No package manager contains terraform v0.11 as demanded by warcannon.

Building terraform from source fails miserably.

If you want people to use this, you are going to have to fix this dependency issue.

**Comment by c6fc** [comment]
You're too cool to download the binary from the Terraform website?

**Comment by un-fuf-a-doo** [comment]
There isn't a linux binary v0.11 on the Terraform website. Try again dick.

**Comment by c6fc** [comment]
This is an advanced tool. It you can't read, I suggest you stick with GUI
tools.

**Comment by c6fc** [comment]
The screenshots didn't make it through via email, but for posterity:

![2021-10-02_18-07](https://user-images.githubusercontent.com/143415/135734955-6d0aad98-c6e1-4d8e-9e92-03456f62b609.png)

![2021-10-02_18-08](https://user-images.githubusercontent.com/143415/135734969-d84b428d-aed4-4b41-bc91-58732fcd72b8.png)

**Comment by un-fuf-a-doo** [comment]
First off, kindly kiss my ass with your 'this is an advanced tool' comment. 

Maybe you should work on advancing your documentation skills. Start by adding a very basic link to the terraform download site pointing to the specific version to use. Maybe don't require such an ancient version of terraform that very well could be vulnerable itself. Unless that is too advanced for you to understand.

And seriously, kiss my ass, you have no idea my skill level on any subject. You clearly excel at BASH.
