### ISSUE TITLE
Any tips / tricks with Terraform setup (specific to this)?

### ISSUE THREAD

**Issue by weisisheng** [c6fc/warcannon#7]
I am a complete noob on TF but not other frameworks.  Installed it, try to initiate and the error is something about no TF file found.

Thanks in advance.

**Comment by c6fc** [comment]
What are you asking?

**Comment by weisisheng** [comment]
Was getting a strange error message re: Terraform.  Found my system installed the latest version.  Reverted back to the recommended one.  Thanks.
